### ISSUE TITLE
Translation & rotation order in transformations

### ISSUE THREAD

**Issue by SteSeg** [openmc-dev/openmc_mcnp_adapter#2]
Hi, I was trying to translate a MCNP input into OpenMC files using the <openmc_mcnp_adapter> tool and I met something unexpected:
the MCNP model I am trying to translate heavily relies on surface transformations (both rotations and translations), checking the <openmc_mcnp_adapter> geometry output file it seems that the tool first translate objects and then it rotates them while it feels "more correct" to follow an inverted order (rotation and then translation) (especially if the new rotation center is not specified).

Model figure coming from the <openmc_mcnp_adapter> tool:
![adapter](https://user-images.githubusercontent.com/92783079/187487017-d0b513d3-15c5-4875-bc0d-909dcf19fe88.png)
Modeled directly with OpenMC with the Python API (translation and then rotation):
![openmc_tr](https://user-images.githubusercontent.com/92783079/187487021-4f23ec0f-86df-430d-a708-4b9399986953.png)
Modeled directly with OpenMC with the Python API (rotation and then translation):
![openmc_rt](https://user-images.githubusercontent.com/92783079/187487020-b0ab5b81-4d0a-45e6-8bb3-c3f427c076b5.png)

They don't look so different but in the first (and second) pictures the yellow (fuchsia) square on the top part of the pictures should be centered in the light green (green) one, just like the pink square is centered in the blank one in the third picture.

**Comment by eepeterson** [comment]
I believe MCNP rotates "first" then translates. Looking at the code in `openmc_conversion.py` we do the opposite. Looking at the ITER C-lite model this issue never comes up and it is so small in the FNG dose benchmark that it wouldn't be graphically noticeable I don't think.

**Comment by tjlaboss** [comment]
That is correct. MCNP rotates about the old origin before translation (or equivalently, rotates about the new origin after translation).

**Comment by paulromano** [comment]
Should be fixed by #3. Let me know if you're still seeing problems
