### ISSUE TITLE
Conversion Failure

### ISSUE THREAD

**Issue by yrrepy** [openmc-dev/openmc_mcnp_adapter#6]
The following line fails conversion:

```
6018  339 -2.0     (((70021 -70022 70023 -70024 -70026 70027 -70028 70029) 6016 -6014):        
       (6014 -6013(70041 -70042 70043 -70044 -70046 70047 -70048 70049)))          7020         imp:n,p,e=1  
```

it is rendered as:
`  <cell id="6018" material="339" region="((70021 -70022 70023 -70024 -70026 70027 -70028 70029 6016 -6014 6014) | (-6013 70041 -70042 70043 -70044 -70046 70047 -70048 70049)) 7020" universe="0"/>`
 
when it should be:
`  <cell id="6018" material="339" region="((70021 -70022 70023 -70024 -70026 70027 -70028 70029 6016 -6014 ) | (6014 -6013 70041 -70042 70043 -70044 -70046 70047 -70048 70049)) 7020" universe="0"/>`
 
The conversion failing with the 6014:
6016 _-6014):(6014_ -6013

**Comment by paulromano** [comment]
Thanks for reporting -- this might actually be a bug in OpenMC itself but I'll dig in and see what I can figure out.

**Comment by paulromano** [comment]
@yrrepy This should be fixed now with the merging of openmc-dev/openmc#2733
